# Generated by Django 4.0.6 on 2022-12-25 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('horario', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(max_length=280)),
                ('dataConclusao', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('AFA', 'A fazer'), ('AND', 'Em andamento'), ('FIN', 'Finalizada')], max_length=3)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.materia')),
            ],
        ),
        migrations.RemoveField(
            model_name='tarefas',
            name='materia',
        ),
        migrations.RemoveField(
            model_name='tarefas',
            name='status',
        ),
        migrations.DeleteModel(
            name='Materias',
        ),
        migrations.DeleteModel(
            name='Status_das_tarefas',
        ),
        migrations.DeleteModel(
            name='Tarefas',
        ),
    ]
