# Generated by Django 4.0.6 on 2022-12-16 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_materias_materia_rename_tarefas_tarefa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='id',
        ),
        migrations.AddField(
            model_name='tarefa',
            name='codigo',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
