# Generated by Django 4.0.6 on 2022-12-21 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_tarefa_id_tarefa_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='descricao',
            field=models.TextField(max_length=280),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('CON', 'Concluída'), ('AND', 'Em andamento'), ('FIN', 'Finalizada')], max_length=3),
        ),
        migrations.DeleteModel(
            name='Status_das_tarefas',
        ),
    ]
