# Generated by Django 4.0.6 on 2022-12-21 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_tarefa_descricao_alter_tarefa_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='dataConclusao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
