# Generated by Django 4.0.6 on 2022-12-21 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_tarefa_dataconclusao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('AFA', 'A fazer'), ('AND', 'Em andamento'), ('FIN', 'Finalizada')], max_length=3),
        ),
    ]
