# Generated by Django 4.0.6 on 2022-12-23 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_tarefa_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='horario',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
